let suggestions = [
    "Programação",
    "Programador",
    "Programador PHP",
    "Programador JAVA",
    "Programador PYTHON",
    "Programador NODEJS",
    "Programador VUEJS",
    "Programador REACTJS",
    "Programador REACT NATIVE",
    "Programador JUNIOR",
    "Programador PLENO",
    "Programador SENIOR",
    "Programador VAGAS",
    "Programador FREELANCER",
    "REDES SOCIAIS",
    "LINKEDIN",
    "INSTAGRAM",
    "GITHUB",
    "FACEBOOK",
    "Como Aprender PHP",
    "Como Aprender JAVA",
    "Como Aprender PYTHON",
    "Como Aprender NODEJS",
    "Como Aprender VUEJS",
    "Como Aprender REACTJS",
    "Como Aprender REACT NATIVE",
    "Como Aprender JUNIOR",
    "Como Aprender PLENO",
    "Como Aprender SENIOR",
    "Como Aprender VAGAS",
    "Como Aprender FREELANCER",
    "Como Aprender HTML E CSS",
    "Cursos De  PHP",
    "Cursos De JAVA",
    "Cursos De PYTHON",
    "Cursos De NODEJS",
    "Cursos De VUEJS",
    "Cursos De REACTJS",
    "Cursos De REACT NATIVE",
    "Cursos De JUNIOR",
    "Cursos De PLENO",
    "Cursos De SENIOR",
    "Cursos De VAGAS",
    "Cursos De FREELANCER",

];
